version: '3'
services:
#   db:
#     image: "postgres:9.6.5"
#     networks:
#       - db_nw
#   flaskapp:
#     build: .
#     volumes:
#       - .:/opt/services/flaskapp/src
#     networks:
#       - db_nw
#       - web_nw
#   nginx:
#     image: "nginx:1.13.5"
#     ports:
#       - "8080:80"
#     volumes:
#       - ./conf.d:/etc/nginx/conf.d
#     networks:
#       - web_nw
# networks:
#   db_nw:
#     driver: bridge
#   web_nw:
#     driver: bridge

  db:
    image: whale1234/idp2:third top
    # container_name: db
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: parola
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    # networks:
    #   - db_nw
  app:
    image: whale1234/idp2:first
    # container_name: app
    # links:
    #   - db
    ports:
      - "5000:5000"
    environment:
      WAIT_HOSTS: db:3306
    deploy:
      placement:
        constraints: [node.role == manager]
    # networks:
    #   - db_nw
    #   - web_nw
  client:
    image: whale1234/idp2:second top
    # container_name: client
    ports:
      - "8084:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    # networks:
    #   - web_nw
# networks:
#   db_nw:
#     driver: bridge
#   web_nw:
#     driver: bridge